services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=astro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/astro_db
      - SECRET_KEY=supersecretkey
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - FACEBOOK_CLIENT_ID=your_facebook_client_id
      - FACEBOOK_CLIENT_SECRET=your_facebook_client_secret
      - INSTAGRAM_CLIENT_ID=your_instagram_client_id
      - INSTAGRAM_CLIENT_SECRET=your_instagram_client_secret
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_smtp_username
      - SMTP_PASSWORD=your_smtp_password
      - EMAIL_FROM=noreply@astrological-ai.com
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: